### ISSUE TITLE
Some questions about the replication of the experiment

### ISSUE THREAD

**Issue by shaoyuyoung** [ise-uiuc/nnsmith#125]
Sorry to bother you again, Jiawei :(

I felt confused after the replication of NNSmith.

In my experiment, NNSmith generated `7686`, `9730`, and `23812` testcases in `4 hours` for `torch`, `ort`, and `TVM` respectively, which exits a big difference from [neuri](https://github.com/ise-uiuc/neuri-artifact) and the report in the [paper](https://dl.acm.org/doi/abs/10.1145/3575693.3575707).  (In my experiment, Neuri can generate `125300` testcases for torch)

For NNSmith and Neuri, I use the docker file you provided. But I reproduced the experiment on the same linux server. 

I can make sure I'm using the same hardware environment so I wonder if it's the version of NNSmith I'm using.

I found you provided two experimental instructions. One in [nnsmith/experiments/README.md](https://github.com/ise-uiuc/nnsmith/tree/main/experiments#experiments), the other one in [docker file](https://nnsmith-asplos.readthedocs.io/en/latest/).

I want to know which version of the code can achieve the SOTA performance of NNSmith？

In addition, if I want to fully understand NNSmith on code aspect. Which version of the source code should I read?

Thx in advance, looking forward to your reply :D

**Comment by ganler** [comment]
Hi Shaoyu, thanks for your interest!

I assume you are saying in the nnsmith artifact nnsmith generate slower while in neuri's nnsmith/neuri generates much faster. IIRC this is because in nnsmith's ASPLOS artifact (as well as earlier versions of nnsmith after that), by default test-cases are generated with an image file visualizing the overall model topology using `dot` and `graphviz`. Until https://github.com/ise-uiuc/nnsmith/commit/40e725d38433535bd11544cf82a81d779ac4cca3, I turned the visualization off as I found it to be a speed bottleneck. Additionally, there has been a lot of similar optimizations and refactorings made in nnsmith after the release of the ASPLOS artifact. 

> I want to know which version of the code can achieve the SOTA performance of NNSmith？

That being said, I would suggest you to use the nnsmith in NeuRI's artifact if you are hoping to benchmark against the latest performance of NNSmith. Meanwhile, you may also modify the code in the ASPLOS artifact to turn off the visualization image generation. Both should work, though the first one might be the most convenient (`mgen.method=symbolic-cinit` is basically almost the nnsmith presented in the ASPLOS paper).

Let me know if you have more questions! Meanwhile I would suggest you to post artifact questions under the artifact repository. :D Good luck with your research!

**Comment by shaoyuyoung** [comment]
Thx for your detailed information :)
Lastly I want to know which version of NNSmith is suitable for reading from scratch. The nightly version on GitHub?

**Comment by ganler** [comment]
If you want to learn about the source code implementation, the current nightly version shall be fine. Let me know if you see anything worth improving.

**Comment by shaoyuyoung** [comment]
Thx very much indeed.,Jiawei :)
I'm looking forward to your new research work:D

**Comment by ganler** [comment]
You are welcome. Maybe `model_gen.py` is a good place to start with: https://github.com/ise-uiuc/nnsmith/blob/main/nnsmith/cli/model_gen.py

**Comment by shaoyuyoung** [comment]
It's just what I thought. 😄 
Thx again!
Have a nice day!
